"""Resolve a universe argument into a list of tickers.

Accepts either a built-in name (``sp500``, ``dow30``) or a path to a file with
one ticker per line (``#`` comments allowed). Built-in lists are packaged
under ``stockscan/universes/`` and regenerated by ``scripts/refresh_universes.py``.
"""

from __future__ import annotations

import os
from importlib import resources
from typing import Optional


def _read_lines(text: str) -> list[str]:
    out = []
    for line in text.splitlines():
        line = line.strip().upper()
        if line and not line.startswith("#"):
            out.append(line)
    return out


def list_builtin_universes() -> list[str]:
    """Names of the packaged universe files (without the .txt extension)."""
    try:
        pkg = resources.files("stockscan").joinpath("universes")
        return sorted(
            p.name[:-4] for p in pkg.iterdir() if p.name.endswith(".txt")
        )
    except Exception:  # pragma: no cover - resource lookup resilience
        return []


def _load_builtin(name: str) -> Optional[list[str]]:
    try:
        res = resources.files("stockscan").joinpath("universes", f"{name}.txt")
        if res.is_file():
            return _read_lines(res.read_text(encoding="utf-8"))
    except Exception:  # pragma: no cover
        pass
    return None


def resolve_universe(name_or_path: str) -> list[str]:
    """Return the ticker list for a built-in name or a file path.

    Resolution order: existing file path first, then built-in name.
    """
    # A path that exists on disk wins.
    if os.path.exists(name_or_path):
        with open(name_or_path, encoding="utf-8") as fh:
            return _read_lines(fh.read())

    # Otherwise treat it as a built-in name (case-insensitive).
    builtin = _load_builtin(name_or_path.lower())
    if builtin is not None:
        return builtin

    available = ", ".join(list_builtin_universes()) or "(none packaged)"
    raise ValueError(
        f"Universe {name_or_path!r} is not a file path or a built-in name. "
        f"Built-in names: {available}."
    )
